channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # specify your desired Python version
  - certifi=2024.6.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - docker-pycreds=0.4.0
  - filelock=3.15.4
  - fsspec=2024.6.1
  - gitdb=4.0.11
  - GitPython=3.1.43
  - idna=3.7
  - Jinja2=3.1.4
  - joblib=1.4.2
  - MarkupSafe=2.1.5
  - mpmath=1.3.0
  - networkx=3.3
  - numpy=2.0.0
  - pillow=10.3.0
  - platformdirs=4.2.2
  - psutil=6.0.0
  - PyYAML=6.0.1
  - requests=2.32.3
  - scikit-learn=1.5.0
  - scipy=1.14.0
  - sentry-sdk=2.7.1
  - setproctitle=1.3.3
  - six=1.16.0
  - sympy=1.12.1
  - threadpoolctl=3.5.0
  - torchvision=0.18.1
  - tqdm=4.66.4
  - typing_extensions=4.12.2
  - urllib3=2.2.2
  - wandb  # removed version to get latest available
  - protobuf  # removed version to get latest available
  - torch  # removed version to get latest available
  - triton  # removed version to get latest available
  - nvidia-cublas-cu12  # removed version to get latest available
  - nvidia-cuda-cupti-cu12  # removed version to get latest available
  - nvidia-cuda-nvrtc-cu12  # removed version to get latest available
  - nvidia-cuda-runtime-cu12  # removed version to get latest available
  - nvidia-cudnn-cu12  # removed version to get latest available
  - nvidia-cufft-cu12  # removed version to get latest available
  - nvidia-curand-cu12  # removed version to get latest available
  - nvidia-cusolver-cu12  # removed version to get latest available
  - nvidia-cusparse-cu12  # removed version to get latest available
  - nvidia-nccl-cu12  # removed version to get latest available
  - nvidia-nvjitlink-cu12  # removed version to get latest available
  - nvidia-nvtx-cu12  # removed version to get latest available
  - smmap  # removed version to get latest available

